### ISSUE TITLE
Save Image doesn't work when added to homescreen

### ISSUE THREAD

**Issue by everestpipkin** [everestpipkin/image-scrubber#15]
On an iPhone 6 at least, save image no longer generates a file when used in offline mode / from 'homescreen'. It does still work if the phone is placed in airplane mode after loading the page in the browser. Something about redirecting the page to an image maybe? Would someone with mobile experience have any ideas on this?

**Comment by onyuwn** [comment]
Could you describe in more detail how you ran into this? I am using an iphone 8 with and ran into no issue scrubbing and downloading an image. Perhaps my ios supports offline browsing differently? I also went into safari web data settings, removed everything it had saved for github pages and had no issue.

**Comment by everestpipkin** [comment]
Were you still running it in the browser, or after running it from the icon generated from the 'Add to Home Screen' option (https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen)? I only ran into this issue from the latter.

**Comment by onyuwn** [comment]
Yes I was accessing the app offline from the icon generated by a2hs. I had no issue.

**Comment by everestpipkin** [comment]
Okay, good to know! If others get this same issue please let me know.

**Comment by everestpipkin** [comment]
Closing this as absolutely nobody else has reported this issue and it might be a problem with my particular jailbroken phone.
