### ISSUE TITLE
Inconsistent and Bad Style Practices

### ISSUE THREAD

**Issue by caelinsutch** [everestpipkin/image-scrubber#25]
There should be a linter to help some style issues. Splitting JS into separate modules  wouldn’t hurt either.

**Comment by caelinsutch** [comment]
Really I think this would require this to be converted into an NPM project to add grunt, eslint and/or other tools to check code style, thoughts?

**Comment by everestpipkin** [comment]
I'm trying to keep this project as light-weight and human readable as possible and don't want to convert to NPM, but I agree that the code needs to be tidied pretty extensively. I think it might need to happen when there is less critical work to do though!

**Comment by wheany** [comment]
While I agree that the code could be modularized better, I also think that it's very valuable that the project is as simple as it is, where all you have to do is to copy the html, js and css files into a directory and it will just work. 

Adding a compilation step increases the barrier to entry for people who want to use the program locally and completely offline and are tech savvy enough to copy some files and open them in a browser, but do not know the javascript build tool ecosystem.

**Comment by SaFrMo** [comment]
Added a possible fix for this in #32!

**Comment by everestpipkin** [comment]
Closing with the merge from #32
