### ISSUE TITLE
Brush smoothing

### ISSUE THREAD

**Issue by lonelymaw** [everestpipkin/image-scrubber#28]
### Current behavior
Currently, the circular brush used for both painting and blurring seems to be disjointed, making fast strokes across the canvas discontinuous and leaving gaps that may leave sensitive information visible.

### Suggested behavior
If possible, smoothing out the brush by repeating it more frequently as the user draws could help mitigate this.

**Comment by bMacSwigg** [comment]
I can work on an improvement to this. My proposal is:
- currently, on every mousemove event we draw a circle at the new mouse position
- instead, we should record the previous position, and interpolate between the previous position and the new position
