### ISSUE TITLE
Flip image

### ISSUE THREAD

**Issue by lonelymaw** [everestpipkin/image-scrubber#30]
### Current behavior
The image can currently be rotated in 90 degree increments, but it cannot be flipped.

### Suggested behavior
I think it's likely users would want to flip images if they can rotate them as well. Having button(s) to do so horizontally and/or vertically could be useful.

**Comment by everestpipkin** [comment]
Rotation is to compensate for images that lose their orientation exif data - because flipping isn't denoted by exif I'm going to shelve it for now.

**Comment by lonelymaw** [comment]
@everestpipkin Ahh, got it! That makes a lot of sense.
