### ISSUE TITLE
interpolatePath check

### ISSUE THREAD

**Issue by SaFrMo** [everestpipkin/image-scrubber#38]
Working on documentation for the project, I'm not sure what [these lines](https://github.com/everestpipkin/image-scrubber/blob/master/scripts/js.js#L229-L235) are for - it looks like the rectangles they're drawing are covered up by the circle drawn in [these lines](https://github.com/everestpipkin/image-scrubber/blob/master/scripts/js.js#L237-L241). Is that first block of code needed for anything or can it be removed? Thanks!

**Comment by everestpipkin** [comment]
I didn’t write it so I could be wrong, but I believe they are both needed
for smooth line interpolation at higher mouse speeds.

**Comment by SaFrMo** [comment]
Great, thanks!
