### ISSUE TITLE
put note about responsible offline usage

### ISSUE THREAD

**Issue by derhuerst** [everestpipkin/image-scrubber#5]
Thanks for building a tool that will hopefully help the public hold government forces accountable!

As [the deployed version](https://everestpipkin.github.io/image-scrubber/) is a public website, it could send your unscrubbed images to a server, exposing people in the photos as well as your IP, browser fingerprint, etc.

- We should use a [`Content-Security-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) of `default-src 'self' ` (and probably a few more directives) to limit the attack surface for creepy middleware (like misbehaving antivirus systems, browser extensions, router-based spyware, etc).
- We should explain people that this is a website, and that they should download it to their computer (what about the phone?) and use it offline. This does not prevent all possible ways data could leak (e.g. service workers uploading later), but it's a first step.
- We should link to trustworthy tools, especially mobile apps, for doing this offline.

**Comment by derhuerst** [comment]
More discussions & background info on privacy implications can be found in [the corresponding HN thread](https://news.ycombinator.com/item?id=23369873).

**Comment by everestpipkin** [comment]
Thank you, useful notes and I agree! Will work on this.

**Comment by everestpipkin** [comment]
Closing this as we've implemented most of these suggestions. :)
